
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jayantharilela
 */
public class page3 extends javax.swing.JFrame {

   /**
    * Creates new form page3
    */
   public page3() {
      initComponents();
      name_display.setText(name_display.getText()+Main.name);
      parid_display.setText(parid_display.getText()+Main.parid);
      cor_display.setText(cor_display.getText()+Main.correct);
      time_display.setText(time_display.getText()+Main.time_elapsed+"s");
      points_display.setText(points_display.getText()+Main.points);
      
   }
   
   
   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name_display = new javax.swing.JLabel();
        parid_display = new javax.swing.JLabel();
        cor_display = new javax.swing.JLabel();
        time_display = new javax.swing.JLabel();
        points_display = new javax.swing.JLabel();
        play_again_button = new javax.swing.JButton();
        high_score_button = new javax.swing.JButton();
        exit_button = new javax.swing.JButton();
        about_button = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(849, 499));
        getContentPane().setLayout(null);

        name_display.setBackground(new java.awt.Color(255, 255, 255));
        name_display.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        name_display.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name_display.setText("Participant Name = ");
        getContentPane().add(name_display);
        name_display.setBounds(220, 40, 390, 30);

        parid_display.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        parid_display.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        parid_display.setText("Participant ID = ");
        getContentPane().add(parid_display);
        parid_display.setBounds(220, 80, 390, 30);

        cor_display.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        cor_display.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cor_display.setText("Correct Words = ");
        getContentPane().add(cor_display);
        cor_display.setBounds(220, 120, 390, 30);

        time_display.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        time_display.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        time_display.setText("Time Elapsed = ");
        getContentPane().add(time_display);
        time_display.setBounds(220, 160, 390, 30);

        points_display.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        points_display.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        points_display.setText("Points Earned = ");
        getContentPane().add(points_display);
        points_display.setBounds(220, 200, 390, 30);

        play_again_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/play_again.png"))); // NOI18N
        play_again_button.setToolTipText("Play again ");
        play_again_button.setBorder(null);
        play_again_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                play_again_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(play_again_button);
        play_again_button.setBounds(600, 340, 90, 80);

        high_score_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/high_score_icon.png"))); // NOI18N
        high_score_button.setToolTipText("High Score");
        high_score_button.setBorder(null);
        high_score_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                high_score_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(high_score_button);
        high_score_button.setBounds(400, 340, 90, 80);

        exit_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
        exit_button.setToolTipText("Exit");
        exit_button.setBorder(null);
        exit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(exit_button);
        exit_button.setBounds(200, 340, 90, 80);

        about_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/about_icon.png"))); // NOI18N
        about_button.setBorder(null);
        about_button.setFocusable(false);
        about_button.setPreferredSize(new java.awt.Dimension(5, 5));
        about_button.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/about_icon.png"))); // NOI18N
        about_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                about_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(about_button);
        about_button.setBounds(770, 30, 62, 53);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background3.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 850, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void play_again_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_play_again_buttonActionPerformed
    String [] a = {""};
      Main.correct=0;
      Main.name="";
      Main.parid="";
      Main.points=0;
      Main.time_elapsed=0;
      try {
         Main.main(a);
      } catch (IOException ex) {
         Logger.getLogger(page3.class.getName()).log(Level.SEVERE, null, ex);
      }
   }//GEN-LAST:event_play_again_buttonActionPerformed

   private void exit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_buttonActionPerformed
   dispose();
   System.exit(1);
   }//GEN-LAST:event_exit_buttonActionPerformed

   private void about_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_about_buttonActionPerformed
      JOptionPane.showMessageDialog(this, "This program has been designed and developed by Jayant Harilela", "About", JOptionPane.INFORMATION_MESSAGE, new javax.swing.ImageIcon(getClass().getResource("/jay.png")));
   }//GEN-LAST:event_about_buttonActionPerformed

   private void high_score_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_high_score_buttonActionPerformed
Main.hs();
   }//GEN-LAST:event_high_score_buttonActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /*
       * Set the Nimbus look and feel
       */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
       * If Nimbus (introduced in Java SE 6) is not available, stay with the
       * default look and feel. For details see
       * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(page3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(page3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(page3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(page3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /*
       * Create and display the form
       */
      java.awt.EventQueue.invokeLater(new Runnable() {

         public void run() {
            new page3().setVisible(true);
         }
      });
   }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton about_button;
    private javax.swing.JLabel background;
    private javax.swing.JLabel cor_display;
    private javax.swing.JButton exit_button;
    private javax.swing.JButton high_score_button;
    private javax.swing.JLabel name_display;
    private javax.swing.JLabel parid_display;
    private javax.swing.JButton play_again_button;
    private javax.swing.JLabel points_display;
    private javax.swing.JLabel time_display;
    // End of variables declaration//GEN-END:variables
}
